# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7909d94ff8ac7cf32b6e159743e189e8"
name = "sync-server-app"
handle = "sync-server-app"
application_url = "https://month-strain-frame-frontpage.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://month-strain-frame-frontpage.trycloudflare.com/auth/callback",
  "https://month-strain-frame-frontpage.trycloudflare.com/auth/shopify/callback",
  "https://month-strain-frame-frontpage.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
